name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.17'
      - name: Build vlckit
        run: |
          #sh compileAndBuildVLCKit.sh -v
          python --version
          echo /Library/Frameworks/Python.framework/Versions/3.*/bin | awk '{print $1;}'
