name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.17'
      - name: Build vlckit
        run: |
          python --version
          which python
          echo /Library/Frameworks/Python.framework/Versions/3.*/bin | awk '{print $1;}'
          brew install cmake
          brew install pkg-config
          brew install libxml2
          brew install libxslt
          brew install libjpeg
          brew install libpng
          brew install libtiff
          brew install libvorbis
          brew install libogg
          brew install libtheora
          brew install libvpx
          brew install ffmpeg
          sh compileAndBuildVLCKit.sh -f -a aarch64
