name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build vlckit
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.17'
        run: |
          #xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
          #sh compileAndBuildVLCKit.sh -v
          echo /Library/Frameworks/Python.framework/Versions/3.*/bin | awk '{print $1;}'
          python --version
